version: '{build}'
pull_requests:
  do_not_increment_build_number: true
configuration:
- Debug
- Release
platform: x64
before_build:
- cmd: >-
    git clone -q https://github.com/jpd002/Play-Build.git C:\Projects\Play-Build

    cd C:\Projects\Play-Build

    git submodule update -q --init --recursive

    git submodule foreach -q "git checkout -q master"

    rd /S /Q Play

    move C:\Projects\Play Play

    nuget.exe restore -verbosity quiet C:\Projects\Play-Build\Play\build_win32\Play.sln
build:
  project: C:\Projects\Play-Build\Play\build_win32\Play.sln
  parallel: true
  verbosity: minimal